version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
